name: Crypto Bot Runner

on:
  schedule:
    - cron: '*/15 * * * *'  # Her 15 dakikada bir çalıştır
  workflow_dispatch:        # Manuel çalıştırma butonu ekle

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: |
          pip install yfinance pandas numpy gspread oauth2client scikit-learn hmmlearn xgboost plotly

      - name: Create JSON Key File
        env:
          GCP_JSON: ${{ secrets.GCP_JSON }}
        run: |
          echo "$GCP_JSON" > service_account.json

      - name: Run Trading Bot
        run: python bot.py
